version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - libtbb-dev

sphinx:
  configuration: docs/source/conf.py

python:
  install:
  - requirements: docs/requirements.txt
  - method: pip
    path: .
