name: pytest
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Set up TBB and mesa
      run: |
        sudo apt update
        sudo apt install libtbb-dev libgles2-mesa-dev
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel pybind11 pytest-xvfb
    - name: Install project
      run: |
        pip install .[tests]
        python setup.py build_ext --inplace
    - name: Run pytest
      run: |
        pytest
