name: Release MacOS Exec
on:
  workflow_dispatch:
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install wheel pyinstaller pybind11
          brew install tbb
    - name: Install project
      run: |
        pip install . -v
        python setup.py build_ext --inplace
      shell: bash
      env:
       CC: gcc-15
       CXX: g++-15
    - name: Build exec
      run: |
        pyinstaller --clean -y spcal.spec
    - name: Set output version
      id: set-output
      run : |
        echo "SPCAL_VERSION=$(python -c "from importlib.metadata import version; print(version('spcal'))")" >> "$env:GITHUB_OUTPUT"
    - name: Upload binary
      id: upload
      run: |
        gh release upload "$env:TAG_NAME" "./dist/spcal_macos_$env:SPCAL_VERSION"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SPCAL_VERSION: ${{ steps.set-output.outputs.SPCAL_VERSION }}
        TAG_NAME: ${{ github.event.release.tag_name }}
